const set = new Set([1,2,4])
console.log(set.size)
const newSet = new Set(set)
const newSet2 = new Set(newSet)
console.log(newSet.size,set ==newSet,newSet2.size,newSet2.has(2))
newSet.forEach(item =>{
    // console.log(item,"item")
    set.delete(4)
    set.add(6)
    console.log('进行中',newSet)
})